environment:
    JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

install:
    - choco upgrade googlechrome

build:
    verbosity: detailed

build_script:
    - gradlew.bat check --info --no-daemon

test_script:
    - gradlew.bat script-tester:integration --info --no-daemon

before_test:
    - java -version

cache:
    - "%USERPROFILE%\\.m2"
    - "%USERPROFILE%\\.gradle"
