environment:
    JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

install:
  - choco upgrade googlechrome --checksum 1450DE87F0289CE725DF1C138BBA2666304FB94BF4476B03C06D058C999D4805

build:
    verbosity: detailed

build_script:
    - gradlew.bat check --info --no-daemon

test_script:
    - gradlew.bat script-tester:integration --info --no-daemon

before_test:
    - java -version

cache:
    - "%USERPROFILE%\\.m2"
    - "%USERPROFILE%\\.gradle"
